<?php

/**
 * @author Andreas Wahlen
 */

define('GEARMAN_VERBOSE_FATAL', 1);
define('GEARMAN_VERBOSE_ERROR', 2);
define('GEARMAN_VERBOSE_INFO', 3);
define('GEARMAN_VERBOSE_DEBUG', 4);
define('GEARMAN_VERBOSE_CRAZY', 5);
define('GEARMAN_VERBOSE_MAX', 6);

// return values

define('GEARMAN_SUCCESS', 0);
define('GEARMAN_IO_WAIT', 1);
define('GEARMAN_SHUTDOWN', 2);
define('GEARMAN_SHUTDOWN_GRACEFUL', 3);
define('GEARMAN_ERRNO', 4);
define('GEARMAN_EVENT', 5);
define('GEARMAN_TOO_MANY_ARGS', 6);
define('GEARMAN_NO_ACTIVE_FDS', 7);
define('GEARMAN_INVALID_MAGIC', 8);
define('GEARMAN_INVALID_COMMAND', 9);
define('GEARMAN_INVALID_PACKET', 10);
define('GEARMAN_UNEXPECTED_PACKET', 11);
define('GEARMAN_GETADDRINFO', 12);
define('GEARMAN_NO_SERVERS', 13);
define('GEARMAN_LOST_CONNECTION', 14);
define('GEARMAN_MEMORY_ALLOCATION_FAILURE', 15);
define('GEARMAN_JOB_EXISTS', 16);
define('GEARMAN_JOB_QUEUE_FULL', 17);
define('GEARMAN_SERVER_ERROR', 18);
define('GEARMAN_WORK_ERROR', 19);
define('GEARMAN_WORK_DATA', 20);
define('GEARMAN_WORK_WARNING', 21);
define('GEARMAN_WORK_STATUS', 22);
define('GEARMAN_WORK_EXCEPTION', 23);
define('GEARMAN_WORK_FAIL', 24);
define('GEARMAN_NOT_CONNECTED', 25);
define('GEARMAN_COULD_NOT_CONNECT', 26);
define('GEARMAN_SEND_IN_PROGRESS', 27);
define('GEARMAN_RECV_IN_PROGRESS', 28);
define('GEARMAN_NOT_FLUSHING', 29);
define('GEARMAN_DATA_TOO_LARGE', 30);
define('GEARMAN_INVALID_FUNCTION_NAME', 31);
define('GEARMAN_INVALID_WORKER_FUNCTION', 32);
define('GEARMAN_NO_REGISTERED_FUNCTIONS', 34);
define('GEARMAN_NO_JOBS', 35);
define('GEARMAN_ECHO_DATA_CORRUPTION', 36);
define('GEARMAN_NEED_WORKLOAD_FN', 37);
define('GEARMAN_PAUSE', 38);
define('GEARMAN_UNKNOWN_STATE', 39);
define('GEARMAN_PTHREAD', 40);
define('GEARMAN_PIPE_EOF', 41);
define('GEARMAN_QUEUE_ERROR', 42);
define('GEARMAN_FLUSH_DATA', 43);
define('GEARMAN_SEND_BUFFER_TOO_SMALL', 44);
define('GEARMAN_IGNORE_PACKET', 45);
define('GEARMAN_UNKNOWN_OPTION', 46);
define('GEARMAN_TIMEOUT', 47);
define('GEARMAN_MAX_RETURN', 53);

// GearmanClient options

define('GEARMAN_CLIENT_ALLOCATED', 1);
define('GEARMAN_CLIENT_NON_BLOCKING', 2);
define('GEARMAN_CLIENT_TASK_IN_USE', 4);
define('GEARMAN_CLIENT_UNBUFFERED_RESULT', 8);
define('GEARMAN_CLIENT_NO_NEW', 16);
define('GEARMAN_CLIENT_FREE_TASKS', 32);

// GearmanClient states

define('GEARMAN_CLIENT_STATE_IDLE', 0);
define('GEARMAN_CLIENT_STATE_NEW', 1);
define('GEARMAN_CLIENT_STATE_SUBMIT', 2);
define('GEARMAN_CLIENT_STATE_PACKET', 3);

// GearmanJob prorities

define('GEARMAN_JOB_PRIORITY_HIGH', 0);
define('GEARMAN_JOB_PRIORITY_NORMAL', 1);
define('GEARMAN_JOB_PRIORITY_LOW', 2);
define('GEARMAN_JOB_PRIORITY_MAX', 3);

// GearmanTask states

define('GEARMAN_TASK_STATE_NEW', 0);
define('GEARMAN_TASK_STATE_SUBMIT', 1);
define('GEARMAN_TASK_STATE_WORKLOAD', 2);
define('GEARMAN_TASK_STATE_WORK', 3);
define('GEARMAN_TASK_STATE_CREATED', 4);
define('GEARMAN_TASK_STATE_DATA', 5);
define('GEARMAN_TASK_STATE_WARNING', 6);
define('GEARMAN_TASK_STATE_STATUS', 7);
define('GEARMAN_TASK_STATE_COMPLETE', 8);
define('GEARMAN_TASK_STATE_EXCEPTION', 9);
define('GEARMAN_TASK_STATE_FAIL', 10);
define('GEARMAN_TASK_STATE_FINISHED', 11);

// GearmanWorker options

define('GEARMAN_WORKER_ALLOCATED', 1);
define('GEARMAN_WORKER_NON_BLOCKING', 2);
define('GEARMAN_WORKER_PACKET_INIT', 4);
define('GEARMAN_WORKER_GRAB_JOB_IN_USE', 8);
define('GEARMAN_WORKER_PRE_SLEEP_IN_USE', 16);
define('GEARMAN_WORKER_WORK_JOB_IN_USE', 32);
define('GEARMAN_WORKER_CHANGE', 64);
define('GEARMAN_WORKER_GRAB_UNIQ', 128);
define('GEARMAN_WORKER_TIMEOUT_RETURN', 256);

// GearmanWorker states

define('GEARMAN_WORKER_STATE_START', 0);
define('GEARMAN_WORKER_STATE_FUNCTION_SEND', 1);
define('GEARMAN_WORKER_STATE_CONNECT', 2);
define('GEARMAN_WORKER_STATE_GRAB_JOB_SEND', 3);
define('GEARMAN_WORKER_STATE_GRAB_JOB_RECV', 4);
define('GEARMAN_WORKER_STATE_PRE_SLEEP', 5);

// Base Gearman configuration

define('GEARMAN_DEFAULT_TCP_HOST', 'localhost');
define('GEARMAN_DEFAULT_TCP_PORT', 4730);
define('GEARMAN_DEFAULT_SOCKET_TIMEOUT', 10);
define('GEARMAN_DEFAULT_SOCKET_SEND_SIZE', 32768);
define('GEARMAN_DEFAULT_SOCKET_RECV_SIZE', 32768);
define('GEARMAN_MAX_ERROR_SIZE', 2048);
define('GEARMAN_PACKET_HEADER_SIZE', 12);
define('GEARMAN_JOB_HANDLE_SIZE', 64);
define('GEARMAN_OPTION_SIZE', 64);
define('GEARMAN_UNIQUE_SIZE', 64);
define('GEARMAN_MAX_COMMAND_ARGS', 8);
define('GEARMAN_ARGS_BUFFER_SIZE', 128);
define('GEARMAN_SEND_BUFFER_SIZE', 8192);
define('GEARMAN_RECV_BUFFER_SIZE', 8192);
define('GEARMAN_WORKER_WAIT_TIMEOUT', 10000);

// connection

define('GEARMAN_NON_BLOCKING', 0);
define('GEARMAN_DONT_TRACK_PACKETS', 1);
define('GEARMAN_CON_READY', 0);
define('GEARMAN_CON_PACKET_IN_USE', 1);
define('GEARMAN_CON_EXTERNAL_FD', 2);
define('GEARMAN_CON_IGNORE_LOST_CONNECTION', 3);
define('GEARMAN_CON_CLOSE_AFTER_FLUSH', 4);
define('GEARMAN_CON_SEND_STATE_NONE', 0);
define('GEARMAN_CON_RECV_STATE_READ_DATA', 2);

// commands

define('GEARMAN_COMMAND_TEXT', 0);
define('GEARMAN_COMMAND_CAN_DO', 1);
define('GEARMAN_COMMAND_CANT_DO', 2);
define('GEARMAN_COMMAND_RESET_ABILITIES', 3);
define('GEARMAN_COMMAND_PRE_SLEEP', 4);
define('GEARMAN_COMMAND_UNUSED', 5);
define('GEARMAN_COMMAND_NOOP', 6);
define('GEARMAN_COMMAND_SUBMIT_JOB', 7);
define('GEARMAN_COMMAND_JOB_CREATED', 8);
define('GEARMAN_COMMAND_GRAB_JOB', 9);
define('GEARMAN_COMMAND_NO_JOB', 10);
define('GEARMAN_COMMAND_JOB_ASSIGN', 11);
define('GEARMAN_COMMAND_WORK_STATUS', 12);
define('GEARMAN_COMMAND_WORK_COMPLETE', 13);
define('GEARMAN_COMMAND_WORK_FAIL', 14);
define('GEARMAN_COMMAND_GET_STATUS', 15);
define('GEARMAN_COMMAND_ECHO_REQ', 16);
define('GEARMAN_COMMAND_ECHO_RES', 17);
define('GEARMAN_COMMAND_SUBMIT_JOB_BG', 18);
define('GEARMAN_COMMAND_ERROR', 19);
define('GEARMAN_COMMAND_STATUS_RES', 20);
define('GEARMAN_COMMAND_SUBMIT_JOB_HIGH', 21);
define('GEARMAN_COMMAND_SET_CLIENT_ID', 22);
define('GEARMAN_COMMAND_CAN_DO_TIMEOUT', 23);
define('GEARMAN_COMMAND_ALL_YOURS', 24);
define('GEARMAN_COMMAND_WORK_EXCEPTION', 25);
define('GEARMAN_COMMAND_OPTION_REQ', 26);
define('GEARMAN_COMMAND_OPTION_RES', 27);
define('GEARMAN_COMMAND_WORK_DATA', 28);
define('GEARMAN_COMMAND_WORK_WARNING', 29);
define('GEARMAN_COMMAND_GRAB_JOB_UNIQ', 30);
define('GEARMAN_COMMAND_JOB_ASSIGN_UNIQ', 31);
define('GEARMAN_COMMAND_SUBMIT_JOB_HIGH_BG', 32);
define('GEARMAN_COMMAND_SUBMIT_JOB_LOW', 33);
define('GEARMAN_COMMAND_SUBMIT_JOB_LOW_BG', 34);
define('GEARMAN_COMMAND_SUBMIT_JOB_SCHED', 35);
define('GEARMAN_COMMAND_SUBMIT_JOB_EPOCH', 36);
define('GEARMAN_COMMAND_MAX', 43);
